services:
  spotify-dashboard:
    build: .
    ports:
      - "80:80"
    volumes:
      # - ./src:/app/src
      # - ./dist:/app/dist
      # - ./App.py:/app/App.py
      # - ./manifest.webmanifest:/app/manifest.webmanifest
      # - ./robots.txt:/app/robots.txt
      - ./:/app